import { mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, relative, resolve } from "node:path";
import {
  enumerateReleasePayload,
  renderEmbeddedAssetsModule,
  type ReleaseAsset,
} from "./generate-standalone-assets";

export const standaloneBuildDirectory = resolve(import.meta.dir, "../build/standalone");
export const standaloneOutputPath = join(standaloneBuildDirectory, "swe-forge");

interface CommandResult {
  readonly exitCode: number;
  readonly stdout: string;
  readonly stderr: string;
}

function rootPath(): string {
  return resolve(import.meta.dir, "..");
}

function fail(message: string): never {
  throw new Error(`standalone build: ${message}`);
}

function normalizedRelativeImport(from: string, to: string): string {
  const value = relative(dirname(from), to).split("\\").join("/");
  return value.startsWith(".") ? value : `./${value}`;
}

function renderEntryModule(entryPath: string, generatedAssetsPath: string, root: string): string {
  const payloadModule = normalizedRelativeImport(
    entryPath,
    join(root, "src/distribution/embedded-payload.ts"),
  );
  const cliModule = normalizedRelativeImport(entryPath, join(root, "src/distribution/standalone-cli.ts"));
  const assetsModule = normalizedRelativeImport(entryPath, generatedAssetsPath);
  return [
    "// Generated by scripts/build-standalone.ts; do not edit.",
    `import { createEmbeddedPayload } from ${JSON.stringify(payloadModule)};`,
    `import { runStandaloneCli } from ${JSON.stringify(cliModule)};`,
    `import { embeddedAssets } from ${JSON.stringify(assetsModule)};`,
    "",
    "process.exitCode = await runStandaloneCli(process.argv.slice(2), createEmbeddedPayload(embeddedAssets));",
    "",
  ].join("\n");
}

function run(command: readonly string[], cwd: string, env: Record<string, string>): CommandResult {
  const result = Bun.spawnSync([...command], {
    cwd,
    env,
    stdout: "pipe",
    stderr: "pipe",
  });
  return {
    exitCode: result.exitCode,
    stdout: new TextDecoder().decode(result.stdout),
    stderr: new TextDecoder().decode(result.stderr),
  };
}

function removeCompileStagingFiles(): void {
  for (const name of readdirSync(standaloneBuildDirectory)) {
    if (name.endsWith(".bun-build")) rmSync(join(standaloneBuildDirectory, name), { force: true });
  }
}

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null;
}

function assertEmbeddedInspection(
  inspectionText: string,
  expectedVersion: string,
  assets: readonly ReleaseAsset[],
): void {
  let value: unknown;
  try {
    value = JSON.parse(inspectionText);
  } catch {
    fail("standalone payload inspection did not return JSON");
  }
  if (!isRecord(value)) fail("standalone payload inspection did not return an object");
  if (value.embedded !== true) fail("standalone payload reports that no payload is embedded");
  if (value.version !== expectedVersion) fail("standalone payload version differs from VERSION");
  if (value.asset_count !== assets.length) fail("standalone payload asset count differs from the inventory");
  if (!Array.isArray(value.assets)) fail("standalone payload inspection has no asset list");

  const actualPaths: string[] = [];
  for (const asset of value.assets) {
    if (!isRecord(asset) || typeof asset.path !== "string" || typeof asset.bytes !== "number") {
      fail("standalone payload inspection has an invalid asset entry");
    }
    if (asset.bytes <= 0) fail(`standalone payload asset is empty: ${asset.path}`);
    actualPaths.push(asset.path);
  }
  const expectedPaths = assets.map((asset) => asset.path);
  if (JSON.stringify(actualPaths) !== JSON.stringify(expectedPaths)) {
    fail("standalone payload paths differ from the generated inventory");
  }
}

function verifyCompiledPayload(
  outputPath: string,
  root: string,
  assets: readonly ReleaseAsset[],
): void {
  const isolated = mkdtempSync(join(tmpdir(), "swe-forge-standalone-build-"));
  const home = join(isolated, "home");
  mkdirSync(home);
  const env: Record<string, string> = {
    HOME: home,
    PATH: process.env.PATH ?? "",
    TMPDIR: isolated,
  };
  try {
    const expectedVersionContents = readFileSync(join(root, "VERSION"), "utf8");
    const expectedVersion = expectedVersionContents.split("\n")[0] ?? "";
    const embeddedVersion = run([outputPath, "payload", "read", "VERSION"], isolated, env);
    if (embeddedVersion.exitCode !== 0) fail(`standalone VERSION read failed: ${embeddedVersion.stderr.trim()}`);
    if (embeddedVersion.stdout !== expectedVersionContents) {
      fail("standalone embedded VERSION content differs from the source VERSION");
    }

    const version = run([outputPath, "version"], isolated, env);
    if (version.exitCode !== 0) fail(`standalone version check failed: ${version.stderr.trim()}`);
    if (version.stdout.split("\n")[0] !== `SWE Forge version: ${expectedVersion}`) {
      fail("standalone reported version differs from embedded VERSION");
    }
    if (version.stdout.includes(root)) fail("standalone version check referenced the repository checkout");

    const inspection = run([outputPath, "payload", "inspect"], isolated, env);
    if (inspection.exitCode !== 0) fail(`standalone payload inspection failed: ${inspection.stderr.trim()}`);
    assertEmbeddedInspection(inspection.stdout, expectedVersion, assets);
  } finally {
    rmSync(isolated, { recursive: true, force: true });
  }
}

export async function buildStandalone(): Promise<{
  readonly outputPath: string;
  readonly assets: readonly ReleaseAsset[];
}> {
  const root = rootPath();
  const generatedAssetsPath = join(standaloneBuildDirectory, "embedded-assets.ts");
  const entryPath = join(standaloneBuildDirectory, "entry.ts");

  mkdirSync(standaloneBuildDirectory, { recursive: true });
  rmSync(standaloneOutputPath, { force: true });
  const assets = enumerateReleasePayload(root);
  // Bun 1.4.0's native compile.assets collides on repeated basenames when
  // given the inventory's source files. A staged directory preserves paths
  // only by adding a copied tree and runtime prefix, so static file imports
  // remain the smaller exact-inventory implementation.
  writeFileSync(generatedAssetsPath, renderEmbeddedAssetsModule(assets, generatedAssetsPath));
  writeFileSync(entryPath, renderEntryModule(entryPath, generatedAssetsPath, root));

  removeCompileStagingFiles();
  try {
    const workingDirectory = process.cwd();
    let result: Awaited<ReturnType<typeof Bun.build>>;
    try {
      // Bun's compile staging file follows the working directory. Keep that
      // generated file beside the ignored standalone output rather than at the
      // repository root.
      process.chdir(standaloneBuildDirectory);
      result = await Bun.build({
        entrypoints: [entryPath],
        format: "esm",
        compile: {
          outfile: standaloneOutputPath,
          autoloadBunfig: false,
          autoloadDotenv: false,
          autoloadPackageJson: false,
          autoloadTsconfig: false,
        },
      });
    } finally {
      process.chdir(workingDirectory);
    }
    if (!result.success) {
      for (const log of result.logs) process.stderr.write(`${log.message}\n`);
      fail("Bun compilation failed");
    }

    verifyCompiledPayload(standaloneOutputPath, root, assets);
  } finally {
    removeCompileStagingFiles();
  }
  return { outputPath: standaloneOutputPath, assets };
}

if (import.meta.main) {
  try {
    const result = await buildStandalone();
    process.stdout.write(`Built standalone executable: ${result.outputPath}\n`);
    process.stdout.write(`Embedded release assets: ${result.assets.length}\n`);
    for (const asset of result.assets) process.stdout.write(`  ${asset.path}\n`);
  } catch (error) {
    process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
    process.exitCode = 1;
  }
}
